databases:
  - name: jobboarddb
    plan: free
    databaseName: jobboard
    user: jobboard
    
services:
  - type: web
    plan: free
    name: jobboard
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn config.wsgi:application -k uvicorn.workers.UvicornWorker' 
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: jobboarddb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "jobboard.onrender.com,*.onrender.com"
      - key: WEB_CONCURRENCY
        value: 4
      - key: USE_WHITENOISE
        value: true
      - key: DEBUG
        value: false