databases:
  - name: jobboarddb
    plan: free
    databaseName: jobboard
    user: jobboard
    
services:
  - type: web
    plan: free
    name: jobboard
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers $WEB_CONCURRENCY' 
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: jobboarddb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "jobboard-qump.onrender.com,*.onrender.com,localhost,127.0.0.1"
      - key: WEB_CONCURRENCY
        value: 4
      - key: USE_WHITENOISE
        value: true
      - key: DEBUG
        value: false
      - key: CORS_ALLOWED_ORIGINS
        value: "https://alx-project-nexus-git-main-joseph-macharias-projects.vercel.app,https://alx-project-nexus.vercel.app"