# Generated by Django 4.2.23 on 2025-08-05 22:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Company name", max_length=200, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Company description and overview"
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True,
                        help_text="Company website URL",
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, help_text="Company contact email", max_length=254
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Company contact phone number",
                        max_length=20,
                    ),
                ),
                ("address", models.TextField(blank=True, help_text="Company address")),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Company logo image",
                        null=True,
                        upload_to="company_logos/",
                    ),
                ),
                (
                    "founded_year",
                    models.PositiveIntegerField(
                        blank=True, help_text="Year the company was founded", null=True
                    ),
                ),
                (
                    "employee_count",
                    models.CharField(
                        blank=True,
                        help_text="Number of employees (e.g., '1-10', '50-100', '500+')",
                        max_length=50,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-friendly version of company name",
                        max_length=220,
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the company is active and can post jobs",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
                "db_table": "company",
                "ordering": ["name"],
            },
        ),
    ]
