# Generated by Django 4.2.23 on 2025-08-06 00:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Job title (e.g., Senior Software Engineer)",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed job description including responsibilities and requirements"
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        help_text="Brief job summary for listings",
                        max_length=500,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="Job location (city, state/country or 'Remote')",
                        max_length=200,
                    ),
                ),
                (
                    "is_remote",
                    models.BooleanField(
                        default=False, help_text="Whether this is a remote position"
                    ),
                ),
                (
                    "salary_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum salary amount",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "salary_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum salary amount",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "salary_type",
                    models.CharField(
                        choices=[
                            ("hourly", "Hourly"),
                            ("monthly", "Monthly"),
                            ("yearly", "Yearly"),
                        ],
                        default="yearly",
                        help_text="Type of salary (hourly, monthly, yearly)",
                        max_length=10,
                    ),
                ),
                (
                    "salary_currency",
                    models.CharField(
                        default="USD",
                        help_text="Currency code (e.g., USD, EUR, GBP)",
                        max_length=3,
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("entry", "Entry Level"),
                            ("junior", "Junior"),
                            ("mid", "Mid Level"),
                            ("senior", "Senior"),
                            ("lead", "Lead"),
                            ("executive", "Executive"),
                        ],
                        default="mid",
                        help_text="Required experience level",
                        max_length=20,
                    ),
                ),
                (
                    "required_skills",
                    models.TextField(
                        blank=True, help_text="Comma-separated list of required skills"
                    ),
                ),
                (
                    "preferred_skills",
                    models.TextField(
                        blank=True, help_text="Comma-separated list of preferred skills"
                    ),
                ),
                (
                    "application_deadline",
                    models.DateTimeField(
                        blank=True, help_text="Deadline for job applications", null=True
                    ),
                ),
                (
                    "external_url",
                    models.URLField(
                        blank=True,
                        help_text="External URL for job application (if not handled internally)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this job is active and accepting applications",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this job should be featured in listings",
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of times this job has been viewed"
                    ),
                ),
                (
                    "applications_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of applications received for this job",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Job categories for classification",
                        related_name="jobs",
                        to="categories.category",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company posting this job",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="jobs.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this job posting",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "industry",
                    models.ForeignKey(
                        help_text="Industry classification",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="categories.industry",
                    ),
                ),
                (
                    "job_type",
                    models.ForeignKey(
                        help_text="Type of employment (full-time, part-time, etc.)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="categories.jobtype",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this job posting",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Job",
                "verbose_name_plural": "Jobs",
                "db_table": "job",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["title"], name="job_title_6bce90_idx"),
                    models.Index(fields=["location"], name="job_locatio_68c449_idx"),
                    models.Index(fields=["is_active"], name="job_is_acti_65cfb7_idx"),
                    models.Index(fields=["created_at"], name="job_created_010237_idx"),
                    models.Index(
                        fields=["company", "is_active"], name="job_company_bf5dfb_idx"
                    ),
                    models.Index(
                        fields=["industry", "job_type"], name="job_industr_1f4aeb_idx"
                    ),
                    models.Index(
                        fields=["location", "is_active"], name="job_locatio_a6d7ec_idx"
                    ),
                ],
            },
        ),
    ]
