# Generated by Django 4.2.23 on 2025-08-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_job"),
    ]

    operations = [
        # Add B-tree indexes for frequently queried fields
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS job_title_location_active_idx ON job (title, location, is_active);",
            reverse_sql="DROP INDEX IF EXISTS job_title_location_active_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS job_created_active_idx ON job (created_at DESC, is_active) WHERE is_active = true;",
            reverse_sql="DROP INDEX IF EXISTS job_created_active_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS job_salary_range_idx ON job (salary_min, salary_max) WHERE salary_min IS NOT NULL OR salary_max IS NOT NULL;",
            reverse_sql="DROP INDEX IF EXISTS job_salary_range_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS job_experience_level_idx ON job (experience_level, is_active);",
            reverse_sql="DROP INDEX IF EXISTS job_experience_level_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS job_remote_location_idx ON job (is_remote, location, is_active);",
            reverse_sql="DROP INDEX IF EXISTS job_remote_location_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS job_featured_created_idx ON job (is_featured DESC, created_at DESC) WHERE is_active = true;",
            reverse_sql="DROP INDEX IF EXISTS job_featured_created_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS job_application_deadline_idx ON job (application_deadline) WHERE application_deadline IS NOT NULL AND is_active = true;",
            reverse_sql="DROP INDEX IF EXISTS job_application_deadline_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS job_views_count_idx ON job (views_count DESC) WHERE is_active = true;",
            reverse_sql="DROP INDEX IF EXISTS job_views_count_idx;"
        ),
        # Add composite indexes for common filter combinations
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS job_industry_type_location_idx ON job (industry_id, job_type_id, location, is_active);",
            reverse_sql="DROP INDEX IF EXISTS job_industry_type_location_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS job_company_created_idx ON job (company_id, created_at DESC, is_active);",
            reverse_sql="DROP INDEX IF EXISTS job_company_created_idx;"
        ),
        # Add indexes for Company model
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS company_name_active_idx ON company (name, is_active);",
            reverse_sql="DROP INDEX IF EXISTS company_name_active_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS company_slug_active_idx ON company (slug, is_active);",
            reverse_sql="DROP INDEX IF EXISTS company_slug_active_idx;"
        ),
    ]
