# Generated by Django 4.2.23 on 2025-08-06 19:52
# Simplified version for SQLite testing

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_add_performance_indexes"),
    ]

    operations = [
        # Add search_vector field for compatibility (will be null in SQLite)
        migrations.AddField(
            model_name='job',
            name='search_vector',
            field=models.TextField(null=True, blank=True),
        ),
        
        migrations.AddField(
            model_name='company',
            name='search_vector',
            field=models.TextField(null=True, blank=True),
        ),
    ]