# Generated by Django 4.2.23 on 2025-08-05 22:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_user_options_alter_user_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="experience_years",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Years of professional experience",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
